//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageStorage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("boxerimages")]
        public string ImagesContainer {
            get {
                return ((string)(this["ImagesContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imageblobs")]
        public string BlobContainer {
            get {
                return ((string)(this["BlobContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DefaultEndpointsProtocol=https;AccountName=boxerimages;AccountKey=W5qV6U9jaOMtcDLWcoUZE/GNy30RlHLmntEJZ9cS+bdRL5FekQvAUyCg6DYzPfHoCDgVsRvGpuJTtvqsOJy4tQ==;BlobEndpoint=https://boxerimages.blob.core.windows.net/;TableEndpoint=https://boxerimages.table.core.windows.net/;QueueEndpoint=https://boxerimages.queue.core.windows.net/;FileEndpoint=https://boxerimages.file.core.windows.net/")]
        public string BlobStorageConnectionString {
            get {
                return ((string)(this["BlobStorageConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://boxerimages.blob.core.windows.net/boxerimages\r\n\t\r\n")]
        public string ImageRootPath {
            get {
                return ((string)(this["ImageRootPath"]));
            }
        }
    }
}
