//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewMember
    {
        public int Id { get; set; }
        public string CrewName { get; set; }
        public string CrewEmail { get; set; }
        public string CrewPhone { get; set; }
    }
}
